import type { z } from 'zod';
import type { SkillTreeSchema } from '../characterSchema';

export const paladinTree: z.infer<typeof SkillTreeSchema>[] = [
    {
        name: 'Aspects',
        skills: [
            {
                name: 'Elemental Wisdom',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Veneration of Justice',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Spark of Hope',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Ward of Fate',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Valiance',
                maxLevel: 10,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Servants of Valor',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Conclave',
                maxLevel: 10,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Fervor',
                maxLevel: 20,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
        ],
    },
    {
        name: 'Templar',
        skills: [
            {
                name: 'Retaliate',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Counterattack',
                maxLevel: 4,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Divine Judgement',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Consecration',
                maxLevel: 5,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Lionheart',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Holy Fire',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Colosseum',
                maxLevel: 20,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
        ],
    },
    {
        name: 'Incarnation',
        skills: [
            {
                name: 'Dragon Jaws',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Solar Flare',
                maxLevel: 20,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Scion',
                maxLevel: 4,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Dragonbone Armor',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Apex Predator',
                maxLevel: 4,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Annihilation',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Dragons Breath',
                maxLevel: 8,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Combustion',
                maxLevel: 5,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
        ],
    },
    {
        name: 'Nephalem',
        skills: [
            {
                name: 'Vessel of Retribution',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Vessel of Judgement',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Solstice and Equinox',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Life and Death',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Absolution',
                maxLevel: 1,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Reverence',
                maxLevel: 1,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
        ],
    },
    {
        name: 'Ritualist',
        skills: [
            {
                name: 'Grim Presence',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Lemures',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Rite of the Restless',
                maxLevel: 1,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Blood Thorns',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Rite of Thorns',
                maxLevel: 1,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Possession',
                maxLevel: 10,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Sanguine Covenant',
                maxLevel: 15,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Frostbite',
                maxLevel: 20,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Transcendence',
                maxLevel: 5,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
        ],
    },
    {
        name: 'Warlock',
        skills: [
            {
                name: 'Mind Flay',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Confluence',
                maxLevel: 1,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Stormlord',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Tainted Blood',
                maxLevel: 15,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Acumen',
                maxLevel: 1,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Slayer',
                maxLevel: 25,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Symphony of Destruction',
                maxLevel: 1,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
        ],
    },
    {
        name: 'Mastery',
        skills: [
            {
                name: 'Meditation',
                maxLevel: 3,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Purity',
                maxLevel: 4,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Melee Devotion',
                maxLevel: 1,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Freedom',
                maxLevel: 5,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Tenacity',
                maxLevel: 5,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Endurance',
                maxLevel: 10,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Continuity',
                maxLevel: 6,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Specialization',
                maxLevel: 10,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Chemistry',
                maxLevel: 5,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
        ],
    },
    {
        name: 'Reward',
        skills: [
            {
                name: 'Divine Apparition',
                maxLevel: 15,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Blessed Life',
                maxLevel: 15,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Dragons Blessing',
                maxLevel: 15,
                currentLevel: 0,
                isPassive: true,
                previous: -1,
                next: 1,
            },
            {
                name: 'Resurrect',
                maxLevel: 15,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
            {
                name: 'Superbeast',
                maxLevel: 15,
                currentLevel: 0,
                isPassive: false,
                previous: -1,
                next: 1,
            },
        ],
    },
];
